const WORDS = {
  5: [
    "PERRO", "GATOS", "CASAS", "LIBRO", "PLAZA", "MUNDO", "PLAYA", "NOCHE",
    "FUEGO", "ARBOL", "SUEÑO", "CAMPO", "VERDE", "LETRA", "PADRE", "MADRE"
  ],
  6: [
    "CAMINO", "TIEMPO", "AMIGOS", "CIUDAD", "FUTURO", "JARDIN", "PUERTA",
    "BLANCO", "MUSICA", "ESTREO", "LENGUA", "PINTOR", "REGALO", "PLANETA"
  ],
  7: [
    "VENTANA", "TECLADO", "CARRERA", "MEMORIA", "DOMINGO", "SISTEMA",
    "PRACTICA", "ESPACIO", "CULTURA", "SEGUNDO", "TRABAJO", "TALENTO"
  ],
  8: [
    "PROYECTO", "LENGUAJE", "COMPUTAR", "PROGRAMA", "PANTALLA", "INTERNET",
    "RECURSOS", "TELEFONO", "MECANICA", "CONEXION", "OPCIONES", "OBJETIVO"
  ]
};